### ISSUE TITLE
ci cleanup

### ISSUE THREAD

**Issue by henryiii** [thaler-lab/Wasserstein#10]
Some suggested cleanup to build-wheels:

* Currently there are three test jobs and three wheel build jobs; now that there's a ci.yml, the test jobs are either no longer needed, or should be moved.
* The cibuildwheel and twine (should use the pypa publish action) should be moved out of a custom script and the action form should be used (can be pinned and updated with Dependabot, too)
* macos-13 (last Intel) and macOS-14 (first AS) images should be used.
* The custom arch stuff in pyproject.toml can then be removed, as native will work fine.

Also, `"wheel"` should not be listed in pyproject.toml, and `backend = setuptools.build_meta` is missing under `[build-system]`.

See https://learn.scientific-python.org/development/guides/repo-review/?repo=thaler-lab%2FWasserstein&branch=master for other ideas.

**Comment by j-s-ashley** [comment]
To break this down into referenceable steps:
 
[build-wheels.yml](https://github.com/thaler-lab/Wasserstein/blob/master/.github/workflows/build-wheels.yml)
- [ ] Remove test jobs
- [ ] Use GHA cibuildwheel instead of build-wheel script
- [ ] Use GHA pypa/publish
- [ ] MacOS-14 support

[pyproject.toml](https://github.com/thaler-lab/Wasserstein/blob/master/pyproject.toml)
- [ ] After MacOS-14, remove custom architecture stuff (`archs = "x86_64 arm64"`)
- [ ] Remove "wheel"
- [ ] Add `backend = setuptools.build_meta`
