### ISSUE TITLE
`sprintf` deprecation

### ISSUE THREAD

**Issue by j-s-ashley** [thaler-lab/Wasserstein#14]
Debugging efforts are currently being slowed by a number of the following deprecation warnings:
`warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.`

Only occurs on MacOS builds.

**Comment by matthewfeickert** [comment]
I wouldn't spend too much time on this right now, as while warnings are useful things to fixup, this isn't fundamentally blocking for the time being.

**Comment by matthewfeickert** [comment]
Notice also how the signatures between [`sprintf`](https://cplusplus.com/reference/cstdio/sprintf/) and [`snprintf`](https://cplusplus.com/reference/cstdio/snprintf/) aren't the same:

* `int sprintf ( char * str, const char * format, ... );`
* `int snprintf ( char * s, size_t n, const char * format, ... );`

so this isn't something that can get fixed with a simple

```
git grep --name-only "sprintf" | xargs sed -i 's/sprintf/snprintf/g'
```

as the signatures would need an additional argument.
