### ISSUE TITLE
OpenMP Library Installation

### ISSUE THREAD

**Issue by j-s-ashley** [thaler-lab/Wasserstein#19]
The current OpenMP library installation method is unreliable.

_Originally posted by @j-s-ashley in https://github.com/thaler-lab/Wasserstein/issues/13#issuecomment-2161488725_
            
Ideally, the method used [here](https://iscinumpy.dev/post/omp-on-high-sierra/) should be used, making use of modern CMake in lieu of `brew`.

**Comment by matthewfeickert** [comment]
@j-s-ashley I believe that you already have a pass of this done on your fork, before you hit Issue https://github.com/thaler-lab/Wasserstein/issues/22. Can you open up a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) from your dev branch there so that we can discuss any ongoing non-NumPy-2.0 issues?
